theme: slate
title: "Materials, Automated"
description: "Automated materials data workflows on request"
permalink: ':title/'
url: 'https://paradimdata.github.io/materialsautomated_sandbox/'

# Author Settings
author: David Elbert # add your name
author-img: Materials-Automated-Logo-small.png # add your photo
about-author: Materials, Automated! is hosted by PARADIM co-PI and Johns Hopkins Professor Tyrel M. McQueen. Our vision is to demonstrate how to automate repetitive data analysis workflows for anyone working with materials data in materials chemistry, physics, or science. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github:  # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  
paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
